# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zen of Devops
name: QingYo
email: me@nobody.known
github_url: None
github_username: NobodyKnown
description: 技术博客，记录日常运维收获·
favicon: favicon.png
repository: None

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: https://ops.1510.cf
# url:http://localhost:4000
## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  - href: /
    label: Home

  - href: /ops.html
    label: Ops
    target: _self
    subnav:
      - subHref: /linux.html
        subLabel: Linux
      - subHref: /container.html
        subLabel: Container
      - subHref: /automatic.html
        subLabel: Automatic

  - href: /dev.html
    label: Dev
    target: _self
    # subnav:
    #   - subHref: /springboot.html
    #     subLabel: SpringBoot
    #   - subHref: /springcloud.html
    #     subLabel: SpringCloud

  # - href: /
  #   label: 中间件
  #   target: _self
  #   subnav:
  #     - subHref: /redis.html
  #       subLabel: Redis
  #     - subHref: /zookeeper.html
  #       subLabel: ZooKeeper
  #     - subHref: /kafka.html
  #       subLabel: Kafka

  - href: /about.html
    label: About

# Sidebar to show popular repo
#喜欢的github仓库fork
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics:
  provider: google baidu sogou
  google:
    tracking_id: 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_ops_keywords: [Linux,Container,kubernetes,Virtualization,Automatic,Unix]
skill_cloud_keywords: [Alibaba,AWS,PrivateCloud]
skill_dev_keywords: [Python,Golang,Java]
skill_db_keywords: [Oracle,MySQL,Influxdb]
skill_bigdata_keywords: [ElasticSearch,Hadoop,HBase]
skill_architecture_keywords: [Topology,Capacity,HA,Backup]
categories: [Linux,Container,kubernetes,Virtualization,Unix,Python,Golang,Java,Alibaba,AWS,PrivateCloud,Oracle,MySQL,Influxdb,ElasticSearch,Hadoop,HBase,Topology,Capacity,HA,Backup]

